name = "PowerFlows"
uuid = "94fada2c-fd9a-4e89-8d82-81405f5cb4f6"
authors = ["Jose Daniel Lara <jdlara@berkeley.edu>"]
version = "0.1.0"

[deps]
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
PowerSystems = "1.15"
julia = "^1.6"
